// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package visioimporter.actions;

import com.aspose.diagram.Diagram;
import com.aspose.diagram.Page;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import visioimporter.impl.VisioExtractor;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class ExtractTextFromRegion extends CustomJavaAction<java.lang.String>
{
	private IMendixObject __Region;
	private visioimporter.proxies.ExtractRegion Region;
	private IMendixObject __ECNFile;
	private visioimporter.proxies.VisioFile ECNFile;

	public ExtractTextFromRegion(IContext context, IMendixObject Region, IMendixObject ECNFile)
	{
		super(context);
		this.__Region = Region;
		this.__ECNFile = ECNFile;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		this.Region = this.__Region == null ? null : visioimporter.proxies.ExtractRegion.initialize(getContext(), __Region);

		this.ECNFile = this.__ECNFile == null ? null : visioimporter.proxies.VisioFile.initialize(getContext(), __ECNFile);

		// BEGIN USER CODE
		Diagram d = VisioExtractor.diagramFromFile(__ECNFile, getContext());
		Page p = d.getPages().getPage("Page-1");
		String text = VisioExtractor.getTextFromRegion(p, this.Region.getxMin().doubleValue(), this.Region.getxMax().doubleValue(),
				this.Region.getyMin().doubleValue(), this.Region.getyMax().doubleValue());
		return text;
		// throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Java action
		// was not implemented");
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ExtractTextFromRegion";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
