// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package visioimporter.actions;

import java.io.InputStream;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import com.aspose.diagram.Diagram;
import com.aspose.diagram.Page;
import com.aspose.diagram.Shape;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import visioimporter.impl.VisioExtractor;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * Should return the ECN number from a visio ECN file
 */
public class ImportTest extends CustomJavaAction<java.lang.String>
{
	private IMendixObject __ECNFile;
	private system.proxies.FileDocument ECNFile;

	public ImportTest(IContext context, IMendixObject ECNFile)
	{
		super(context);
		this.__ECNFile = ECNFile;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		this.ECNFile = this.__ECNFile == null ? null : system.proxies.FileDocument.initialize(getContext(), __ECNFile);

		// BEGIN USER CODE
		
		// get all text shapes in document
		Diagram d = VisioExtractor.diagramFromFile(__ECNFile, getContext());	
		
		Page p = d.getPages().getPage("Page-1");
		
		String text = VisioExtractor.getTextFromRegion(p, 10, 14.5, 20.25, 20.875);
		return text;
		
//		throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Java action was not implemented");
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ImportTest";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
